[package]
edition = "2021"
name = "resistor-color"
version = "1.0.0"

[dependencies]
int-enum = "0.4.0"
enum-iterator = "1.1.1"
num-traits = "0.2"
num-derive = "0.3"
fmt = "0.1.0"
strum = "0.24.1"
strum_macros = "0.24.2"
